# 站点名称
site_name: 'YOLO_v1'
# 仓库链接
repo_url: https://github.com/zjZSTU/YOLO_v1.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2020, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.2.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md
    - 架构解析: '架构解析.md'
    - 数据集: '数据集.md'
    - YOLO模型: 'YOLO模型.md'
    - 损失函数: '损失函数.md'
    - 模型训练: '模型训练.md'
    - 训练日志: 
        - '定位数据集': 'location-log.md'
        - 'VOC 07': 'voc-07-log.md'